# Generated by Django 3.0.8 on 2020-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.URLField(max_length=16)),
                ('com', models.URLField(max_length=16)),
                ('eu', models.URLField(max_length=16)),
                ('net', models.URLField(max_length=16)),
                ('org', models.URLField(max_length=16)),
                ('info', models.URLField(max_length=16)),
                ('biz', models.URLField(max_length=16)),
            ],
        ),
    ]
