# Generated by Django 3.0.8 on 2020-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainsmodel',
            name='biz',
            field=models.URLField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='domainsmodel',
            name='com',
            field=models.URLField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='domainsmodel',
            name='eu',
            field=models.URLField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='domainsmodel',
            name='info',
            field=models.URLField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='domainsmodel',
            name='it',
            field=models.URLField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='domainsmodel',
            name='net',
            field=models.URLField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='domainsmodel',
            name='org',
            field=models.URLField(max_length=16, unique=True),
        ),
    ]
